"""
A bone representing a country selection input field in a web application or form.

The SelectCountryBone is designed to provide a user-friendly way to select a country from a predefined list of
countries. It inherits from the BaseBone class and extends it to support country-specific functionalities,
such as displaying country names and handling country codes (e.g., ISO 3166-1 alpha-2 or alpha-3).
"""
from viur.core.bones.select import SelectBone


class SelectCountryBone(SelectBone):
    """
    A bone representing a country selection input field in a web application or form.

    The SelectCountryBone is designed to provide a user-friendly way to select a country from a predefined list of
    countries. It inherits from the BaseBone class and extends it to support country-specific functionalities,
    such as displaying country names and handling country codes (e.g., ISO 3166-1 alpha-2 or alpha-3).

    :param codes: The version of the ISO-Codes, either 2 or 3
    :param values: Optional, either a str representing a predefined group (currently "dach" and "eu"), a list of
         ISO-Codes (must match the Code-Length from `codes`), or a dict with matching iso-codes as keys and
         the full country-names as values.

    .. seealso::
        https://www.iso.org/obp/ui/#search/code/
    """

    ISO3CODES = {
        "abw": "Aruba",
        "afg": "Afghanistan",
        "ago": "Angola",
        "aia": "Anguilla",
        "ala": "Åland Islands",
        "alb": "Albania",
        "and": "Andorra",
        "are": "United Arab Emirates",
        "arg": "Argentina",
        "arm": "Armenia",
        "asm": "American Samoa",
        "ata": "Antarctica",
        "atf": "French Southern Territories",
        "atg": "Antigua and Barbuda",
        "aus": "Australia",
        "aut": "Austria",
        "aze": "Azerbaijan",
        "bdi": "Burundi",
        "bel": "Belgium",
        "ben": "Benin",
        "bes": "Bonaire, Sint Eustatius and Saba",
        "bfa": "Burkina Faso",
        "bgd": "Bangladesh",
        "bgr": "Bulgaria",
        "bhr": "Bahrain",
        "bhs": "Bahamas",
        "bih": "Bosnia and Herzegovina",
        "blm": "Saint Barthélemy",
        "blr": "Belarus",
        "blz": "Belize",
        "bmu": "Bermuda",
        "bol": "Bolivia",
        "bra": "Brazil",
        "brb": "Barbados",
        "brn": "Brunei",
        "btn": "Bhutan",
        "bvt": "Bouvet Island",
        "bwa": "Botswana",
        "caf": "Central African Republic",
        "can": "Canada",
        "cck": "Cocos (Keeling) Islands",
        "che": "Switzerland",
        "chl": "Chile",
        "chn": "China",
        "civ": "Côte d'Ivoire",
        "cmr": "Cameroon",
        "cod": "Congo Democratic Republic",
        "cog": "Congo Republic",
        "cok": "Cook Islands",
        "col": "Colombia",
        "com": "Comoros",
        "cpv": "Cabo Verde",
        "cri": "Costa Rica",
        "cub": "Cuba",
        "cuw": "Curaçao",
        "cxr": "Christmas Island",
        "cym": "Cayman Islands",
        "cyp": "Cyprus",
        "cze": "Czechia",
        "deu": "Germany",
        "dji": "Djibouti",
        "dma": "Dominica",
        "dnk": "Denmark",
        "dom": "Dominican Republic",
        "dza": "Algeria",
        "ecu": "Ecuador",
        "egy": "Egypt",
        "eri": "Eritrea",
        "esh": "Western Sahara",
        "esp": "Spain",
        "est": "Estonia",
        "eth": "Ethiopia",
        "fin": "Finland",
        "fji": "Fiji",
        "flk": "Falkland Islands",
        "fra": "France",
        "fro": "Faroe Islands",
        "fsm": "Micronesia",
        "gab": "Gabon",
        "gbr": "United Kingdom",
        "geo": "Georgia",
        "ggy": "Guernsey",
        "gha": "Ghana",
        "gib": "Gibraltar",
        "gin": "Guinea",
        "glp": "Guadeloupe",
        "gmb": "Gambia",
        "gnb": "Guinea-Bissau",
        "gnq": "Equatorial Guinea",
        "grc": "Greece",
        "grd": "Grenada",
        "grl": "Greenland",
        "gtm": "Guatemala",
        "guf": "French Guiana",
        "gum": "Guam",
        "guy": "Guyana",
        "hkg": "Hong Kong",
        "hmd": "Heard Island and McDonald Islands",
        "hnd": "Honduras",
        "hrv": "Croatia",
        "hti": "Haiti",
        "hun": "Hungary",
        "idn": "Indonesia",
        "imn": "Isle of Man",
        "ind": "India",
        "iot": "British Indian Ocean Territory",
        "irl": "Ireland",
        "irn": "Iran",
        "irq": "Iraq",
        "isl": "Iceland",
        "isr": "Israel",
        "ita": "Italy",
        "jam": "Jamaica",
        "jey": "Jersey",
        "jor": "Jordan",
        "jpn": "Japan",
        "kaz": "Kazakhstan",
        "ken": "Kenya",
        "kgz": "Kyrgyzstan",
        "khm": "Cambodia",
        "kir": "Kiribati",
        "kna": "Saint Kitts and Nevis",
        "kor": "Korea South",
        "kwt": "Kuwait",
        "lao": "Laos",
        "lbn": "Lebanon",
        "lbr": "Liberia",
        "lby": "Libya",
        "lca": "Saint Lucia",
        "lie": "Liechtenstein",
        "lka": "Sri Lanka",
        "lso": "Lesotho",
        "ltu": "Lithuania",
        "lux": "Luxembourg",
        "lva": "Latvia",
        "mac": "Macao",
        "maf": "Saint Martin",
        "mar": "Morocco",
        "mco": "Monaco",
        "mda": "Moldova",
        "mdg": "Madagascar",
        "mdv": "Maldives",
        "mex": "Mexico",
        "mhl": "Marshall Islands",
        "mkd": "North Macedonia",
        "mli": "Mali",
        "mlt": "Malta",
        "mmr": "Myanmar",
        "mne": "Montenegro",
        "mng": "Mongolia",
        "mnp": "Northern Mariana Islands",
        "moz": "Mozambique",
        "mrt": "Mauritania",
        "msr": "Montserrat",
        "mtq": "Martinique",
        "mus": "Mauritius",
        "mwi": "Malawi",
        "mys": "Malaysia",
        "myt": "Mayotte",
        "nam": "Namibia",
        "ncl": "New Caledonia",
        "ner": "Niger",
        "nfk": "Norfolk Island",
        "nga": "Nigeria",
        "nic": "Nicaragua",
        "niu": "Niue",
        "nld": "Netherlands (Kingdom of the)",
        "nor": "Norway",
        "npl": "Nepal",
        "nru": "Naoero",
        "nzl": "New Zealand",
        "omn": "Oman",
        "pak": "Pakistan",
        "pan": "Panama",
        "pcn": "Pitcairn",
        "per": "Peru",
        "phl": "Philippines",
        "plw": "Palau",
        "png": "Papua New Guinea",
        "pol": "Poland",
        "pri": "Puerto Rico",
        "prk": "Korea North",
        "prt": "Portugal",
        "pry": "Paraguay",
        "pse": "Palestine, State of",
        "pyf": "French Polynesia",
        "qat": "Qatar",
        "reu": "Réunion",
        "rou": "Romania",
        "rus": "Russia",
        "rwa": "Rwanda",
        "sau": "Saudi Arabia",
        "sdn": "Sudan",
        "sen": "Senegal",
        "sgp": "Singapore",
        "sgs": "South Georgia and the South Sandwich Islands",
        "shn": "Saint Helena Ascension and Tristan da Cunha",
        "sjm": "Svalbard and Jan Mayen",
        "slb": "Solomon Islands",
        "sle": "Sierra Leone",
        "slv": "El Salvador",
        "smr": "San Marino",
        "som": "Somalia",
        "spm": "Saint Pierre and Miquelon",
        "srb": "Serbia",
        "ssd": "South Sudan",
        "stp": "Sao Tome and Principe",
        "sur": "Suriname",
        "svk": "Slovakia",
        "svn": "Slovenia",
        "swe": "Sweden",
        "swz": "Eswatini",
        "sxm": "Sint Maarten",
        "syc": "Seychelles",
        "syr": "Syria",
        "tca": "Turks and Caicos Islands",
        "tcd": "Chad",
        "tgo": "Togo",
        "tha": "Thailand",
        "tjk": "Tajikistan",
        "tkl": "Tokelau",
        "tkm": "Turkmenistan",
        "tls": "Timor-Leste",
        "ton": "Tonga",
        "tto": "Trinidad and Tobago",
        "tun": "Tunisia",
        "tur": "Türkiye",
        "tuv": "Tuvalu",
        "twn": "Taiwan",
        "tza": "Tanzania",
        "uga": "Uganda",
        "ukr": "Ukraine",
        "umi": "United States Minor Outlying Islands",
        "ury": "Uruguay",
        "usa": "United States",
        "uzb": "Uzbekistan",
        "vat": "Holy See",
        "vct": "Saint Vincent and the Grenadines",
        "ven": "Venezuela",
        "vgb": "British Virgin Islands",
        "vir": "Virgin Islands (U.S.)",
        "vnm": "Vietnam",
        "vut": "Vanuatu",
        "wlf": "Wallis and Futuna",
        "wsm": "Samoa",
        "yem": "Yemen",
        "zaf": "South Africa",
        "zmb": "Zambia",
        "zwe": "Zimbabwe"
    }
    """
    ISO 3166-1 alpha-3 (commonly referred to as ISO3) is a part of the ISO 3166 standard, which defines three-letter
    codes to represent countries.
    """

    ISO2CODES = {
        "ad": "Andorra",
        "ae": "United Arab Emirates",
        "af": "Afghanistan",
        "ag": "Antigua and Barbuda",
        "ai": "Anguilla",
        "al": "Albania",
        "am": "Armenia",
        "ao": "Angola",
        "aq": "Antarctica",
        "ar": "Argentina",
        "as": "American Samoa",
        "at": "Austria",
        "au": "Australia",
        "aw": "Aruba",
        "ax": "Åland Islands",
        "az": "Azerbaijan",
        "ba": "Bosnia and Herzegovina",
        "bb": "Barbados",
        "bd": "Bangladesh",
        "be": "Belgium",
        "bf": "Burkina Faso",
        "bg": "Bulgaria",
        "bh": "Bahrain",
        "bi": "Burundi",
        "bj": "Benin",
        "bl": "Saint Barthélemy",
        "bm": "Bermuda",
        "bn": "Brunei",
        "bo": "Bolivia",
        "bq": "Bonaire, Sint Eustatius and Saba",
        "br": "Brazil",
        "bs": "Bahamas",
        "bt": "Bhutan",
        "bv": "Bouvet Island",
        "bw": "Botswana",
        "by": "Belarus",
        "bz": "Belize",
        "ca": "Canada",
        "cc": "Cocos (Keeling) Islands",
        "cd": "Congo Democratic Republic",
        "cf": "Central African Republic",
        "cg": "Congo Republic",
        "ch": "Switzerland",
        "ci": "Côte d'Ivoire",
        "ck": "Cook Islands",
        "cl": "Chile",
        "cm": "Cameroon",
        "cn": "China",
        "co": "Colombia",
        "cr": "Costa Rica",
        "cu": "Cuba",
        "cv": "Cabo Verde",
        "cw": "Curaçao",
        "cx": "Christmas Island",
        "cy": "Cyprus",
        "cz": "Czechia",
        "de": "Germany",
        "dj": "Djibouti",
        "dk": "Denmark",
        "dm": "Dominica",
        "do": "Dominican Republic",
        "dz": "Algeria",
        "ec": "Ecuador",
        "ee": "Estonia",
        "eg": "Egypt",
        "eh": "Western Sahara",
        "er": "Eritrea",
        "es": "Spain",
        "et": "Ethiopia",
        "fi": "Finland",
        "fj": "Fiji",
        "fk": "Falkland Islands",
        "fm": "Micronesia",
        "fo": "Faroe Islands",
        "fr": "France",
        "ga": "Gabon",
        "gb": "United Kingdom",
        "gd": "Grenada",
        "ge": "Georgia",
        "gf": "French Guiana",
        "gg": "Guernsey",
        "gh": "Ghana",
        "gi": "Gibraltar",
        "gl": "Greenland",
        "gm": "Gambia",
        "gn": "Guinea",
        "gp": "Guadeloupe",
        "gq": "Equatorial Guinea",
        "gr": "Greece",
        "gs": "South Georgia and the South Sandwich Islands",
        "gt": "Guatemala",
        "gu": "Guam",
        "gw": "Guinea-Bissau",
        "gy": "Guyana",
        "hk": "Hong Kong",
        "hm": "Heard Island and McDonald Islands",
        "hn": "Honduras",
        "hr": "Croatia",
        "ht": "Haiti",
        "hu": "Hungary",
        "id": "Indonesia",
        "ie": "Ireland",
        "il": "Israel",
        "im": "Isle of Man",
        "in": "India",
        "io": "British Indian Ocean Territory",
        "iq": "Iraq",
        "ir": "Iran",
        "is": "Iceland",
        "it": "Italy",
        "je": "Jersey",
        "jm": "Jamaica",
        "jo": "Jordan",
        "jp": "Japan",
        "ke": "Kenya",
        "kg": "Kyrgyzstan",
        "kh": "Cambodia",
        "ki": "Kiribati",
        "km": "Comoros",
        "kn": "Saint Kitts and Nevis",
        "kp": "Korea North",
        "kr": "Korea South",
        "kw": "Kuwait",
        "ky": "Cayman Islands",
        "kz": "Kazakhstan",
        "la": "Laos",
        "lb": "Lebanon",
        "lc": "Saint Lucia",
        "li": "Liechtenstein",
        "lk": "Sri Lanka",
        "lr": "Liberia",
        "ls": "Lesotho",
        "lt": "Lithuania",
        "lu": "Luxembourg",
        "lv": "Latvia",
        "ly": "Libya",
        "ma": "Morocco",
        "mc": "Monaco",
        "md": "Moldova",
        "me": "Montenegro",
        "mf": "Saint Martin",
        "mg": "Madagascar",
        "mh": "Marshall Islands",
        "mk": "North Macedonia",
        "ml": "Mali",
        "mm": "Myanmar",
        "mn": "Mongolia",
        "mo": "Macao",
        "mp": "Northern Mariana Islands",
        "mq": "Martinique",
        "mr": "Mauritania",
        "ms": "Montserrat",
        "mt": "Malta",
        "mu": "Mauritius",
        "mv": "Maldives",
        "mw": "Malawi",
        "mx": "Mexico",
        "my": "Malaysia",
        "mz": "Mozambique",
        "na": "Namibia",
        "nc": "New Caledonia",
        "ne": "Niger",
        "nf": "Norfolk Island",
        "ng": "Nigeria",
        "ni": "Nicaragua",
        "nl": "Netherlands (Kingdom of the)",
        "no": "Norway",
        "np": "Nepal",
        "nr": "Naoero",
        "nu": "Niue",
        "nz": "New Zealand",
        "om": "Oman",
        "pa": "Panama",
        "pe": "Peru",
        "pf": "French Polynesia",
        "pg": "Papua New Guinea",
        "ph": "Philippines",
        "pk": "Pakistan",
        "pl": "Poland",
        "pm": "Saint Pierre and Miquelon",
        "pn": "Pitcairn",
        "pr": "Puerto Rico",
        "ps": "Palestine, State of",
        "pt": "Portugal",
        "pw": "Palau",
        "py": "Paraguay",
        "qa": "Qatar",
        "re": "Réunion",
        "ro": "Romania",
        "rs": "Serbia",
        "ru": "Russia",
        "rw": "Rwanda",
        "sa": "Saudi Arabia",
        "sb": "Solomon Islands",
        "sc": "Seychelles",
        "sd": "Sudan",
        "se": "Sweden",
        "sg": "Singapore",
        "sh": "Saint Helena Ascension and Tristan da Cunha",
        "si": "Slovenia",
        "sj": "Svalbard and Jan Mayen",
        "sk": "Slovakia",
        "sl": "Sierra Leone",
        "sm": "San Marino",
        "sn": "Senegal",
        "so": "Somalia",
        "sr": "Suriname",
        "ss": "South Sudan",
        "st": "Sao Tome and Principe",
        "sv": "El Salvador",
        "sx": "Sint Maarten",
        "sy": "Syria",
        "sz": "Eswatini",
        "tc": "Turks and Caicos Islands",
        "td": "Chad",
        "tf": "French Southern Territories",
        "tg": "Togo",
        "th": "Thailand",
        "tj": "Tajikistan",
        "tk": "Tokelau",
        "tl": "Timor-Leste",
        "tm": "Turkmenistan",
        "tn": "Tunisia",
        "to": "Tonga",
        "tr": "Türkiye",
        "tt": "Trinidad and Tobago",
        "tv": "Tuvalu",
        "tw": "Taiwan",
        "tz": "Tanzania",
        "ua": "Ukraine",
        "ug": "Uganda",
        "um": "United States Minor Outlying Islands",
        "us": "United States",
        "uy": "Uruguay",
        "uz": "Uzbekistan",
        "va": "Holy See",
        "vc": "Saint Vincent and the Grenadines",
        "ve": "Venezuela",
        "vg": "British Virgin Islands",
        "vi": "Virgin Islands (U.S.)",
        "vn": "Vietnam",
        "vu": "Vanuatu",
        "wf": "Wallis and Futuna",
        "ws": "Samoa",
        "ye": "Yemen",
        "yt": "Mayotte",
        "za": "South Africa",
        "zm": "Zambia",
        "zw": "Zimbabwe"
    }
    """
    The ISO 2 country code (also known as ISO 3166-1 alpha-2) is an international standard consisting of two-letter
    codes used to identify countries.
    """
    ISO3TOISO2 = {  # Convert iso3 to iso2 codes
        "abw": "aw",
        "afg": "af",
        "ago": "ao",
        "aia": "ai",
        "ala": "ax",
        "alb": "al",
        "and": "ad",
        "are": "ae",
        "arg": "ar",
        "arm": "am",
        "asm": "as",
        "ata": "aq",
        "atf": "tf",
        "atg": "ag",
        "aus": "au",
        "aut": "at",
        "aze": "az",
        "bdi": "bi",
        "bel": "be",
        "ben": "bj",
        "bes": "bq",
        "bfa": "bf",
        "bgd": "bd",
        "bgr": "bg",
        "bhr": "bh",
        "bhs": "bs",
        "bih": "ba",
        "blm": "bl",
        "blr": "by",
        "blz": "bz",
        "bmu": "bm",
        "bol": "bo",
        "bra": "br",
        "brb": "bb",
        "brn": "bn",
        "btn": "bt",
        "bvt": "bv",
        "bwa": "bw",
        "caf": "cf",
        "can": "ca",
        "cck": "cc",
        "che": "ch",
        "chl": "cl",
        "chn": "cn",
        "civ": "ci",
        "cmr": "cm",
        "cod": "cd",
        "cog": "cg",
        "cok": "ck",
        "col": "co",
        "com": "km",
        "cpv": "cv",
        "cri": "cr",
        "cub": "cu",
        "cuw": "cw",
        "cxr": "cx",
        "cym": "ky",
        "cyp": "cy",
        "cze": "cz",
        "deu": "de",
        "dji": "dj",
        "dma": "dm",
        "dnk": "dk",
        "dom": "do",
        "dza": "dz",
        "ecu": "ec",
        "egy": "eg",
        "eri": "er",
        "esh": "eh",
        "esp": "es",
        "est": "ee",
        "eth": "et",
        "fin": "fi",
        "fji": "fj",
        "flk": "fk",
        "fra": "fr",
        "fro": "fo",
        "fsm": "fm",
        "gab": "ga",
        "gbr": "gb",
        "geo": "ge",
        "ggy": "gg",
        "gha": "gh",
        "gib": "gi",
        "gin": "gn",
        "glp": "gp",
        "gmb": "gm",
        "gnb": "gw",
        "gnq": "gq",
        "grc": "gr",
        "grd": "gd",
        "grl": "gl",
        "gtm": "gt",
        "guf": "gf",
        "gum": "gu",
        "guy": "gy",
        "hkg": "hk",
        "hmd": "hm",
        "hnd": "hn",
        "hrv": "hr",
        "hti": "ht",
        "hun": "hu",
        "idn": "id",
        "imn": "im",
        "ind": "in",
        "iot": "io",
        "irl": "ie",
        "irn": "ir",
        "irq": "iq",
        "isl": "is",
        "isr": "il",
        "ita": "it",
        "jam": "jm",
        "jey": "je",
        "jor": "jo",
        "jpn": "jp",
        "kaz": "kz",
        "ken": "ke",
        "kgz": "kg",
        "khm": "kh",
        "kir": "ki",
        "kna": "kn",
        "kor": "kr",
        "kwt": "kw",
        "lao": "la",
        "lbn": "lb",
        "lbr": "lr",
        "lby": "ly",
        "lca": "lc",
        "lie": "li",
        "lka": "lk",
        "lso": "ls",
        "ltu": "lt",
        "lux": "lu",
        "lva": "lv",
        "mac": "mo",
        "maf": "mf",
        "mar": "ma",
        "mco": "mc",
        "mda": "md",
        "mdg": "mg",
        "mdv": "mv",
        "mex": "mx",
        "mhl": "mh",
        "mkd": "mk",
        "mli": "ml",
        "mlt": "mt",
        "mmr": "mm",
        "mne": "me",
        "mng": "mn",
        "mnp": "mp",
        "moz": "mz",
        "mrt": "mr",
        "msr": "ms",
        "mtq": "mq",
        "mus": "mu",
        "mwi": "mw",
        "mys": "my",
        "myt": "yt",
        "nam": "na",
        "ncl": "nc",
        "ner": "ne",
        "nfk": "nf",
        "nga": "ng",
        "nic": "ni",
        "niu": "nu",
        "nld": "nl",
        "nor": "no",
        "npl": "np",
        "nru": "nr",
        "nzl": "nz",
        "omn": "om",
        "pak": "pk",
        "pan": "pa",
        "pcn": "pn",
        "per": "pe",
        "phl": "ph",
        "plw": "pw",
        "png": "pg",
        "pol": "pl",
        "pri": "pr",
        "prk": "kp",
        "prt": "pt",
        "pry": "py",
        "pse": "ps",
        "pyf": "pf",
        "qat": "qa",
        "reu": "re",
        "rou": "ro",
        "rus": "ru",
        "rwa": "rw",
        "sau": "sa",
        "sdn": "sd",
        "sen": "sn",
        "sgp": "sg",
        "sgs": "gs",
        "shn": "sh",
        "sjm": "sj",
        "slb": "sb",
        "sle": "sl",
        "slv": "sv",
        "smr": "sm",
        "som": "so",
        "spm": "pm",
        "srb": "rs",
        "ssd": "ss",
        "stp": "st",
        "sur": "sr",
        "svk": "sk",
        "svn": "si",
        "swe": "se",
        "swz": "sz",
        "sxm": "sx",
        "syc": "sc",
        "syr": "sy",
        "tca": "tc",
        "tcd": "td",
        "tgo": "tg",
        "tha": "th",
        "tjk": "tj",
        "tkl": "tk",
        "tkm": "tm",
        "tls": "tl",
        "ton": "to",
        "tto": "tt",
        "tun": "tn",
        "tur": "tr",
        "tuv": "tv",
        "twn": "tw",
        "tza": "tz",
        "uga": "ug",
        "ukr": "ua",
        "umi": "um",
        "ury": "uy",
        "usa": "us",
        "uzb": "uz",
        "vat": "va",
        "vct": "vc",
        "ven": "ve",
        "vgb": "vg",
        "vir": "vi",
        "vnm": "vn",
        "vut": "vu",
        "wlf": "wf",
        "wsm": "ws",
        "yem": "ye",
        "zaf": "za",
        "zmb": "zm",
        "zwe": "zw",
    }
    """A Map of ISO3 to ISO2 country codes"""

    ISO2TOISO3 = {v: k for k, v in ISO3TOISO2.items()}  # Build the invert map
    """A built Map of ISO2 to ISO3 country codes"""

    subgroup_mappings = {
        "dach": ["de", "at", "ch"],
        "eu": ["at", "be", "bg", "hr", "cy", "cz", "dk", "ee", "fi", "fr", "de", "gr", "hu", "ie", "it", "lv", "lt",
               "lu", "mt", "nl", "pl", "pt", "ro", "sk", "si", "es", "se"],
    }

    type = "select.country"
    ISO2 = 2
    ISO3 = 3

    def __init__(self, *, descr="Country", codes=ISO2, values=None, **kwargs):
        assert codes in [self.ISO2, self.ISO3]
        # assert values is None

        if values is None:
            values = dict(
                sorted((self.ISO2CODES if codes == self.ISO2 else self.ISO3CODES).items(), key=lambda i: i[1]))
        else:
            if isinstance(values, str):
                values = self.subgroup_mappings[values]
                if codes == self.ISO3:
                    values = [self.ISO2TOISO3[i] for i in values]
            if isinstance(values, list):
                if codes == self.ISO2:
                    values = {k: self.ISO2CODES[k] for k in values}
                elif codes == self.ISO3:
                    values = {k: self.ISO3CODES[k] for k in values}
            if isinstance(values, dict):
                values = dict(sorted(values.items(), key=lambda i: i[1]))

        super().__init__(
            values=values,
            descr=descr,
            **kwargs
        )

        self.codes = codes

    def singleValueUnserialize(self, val):
        """
        Unserializes a single value, converting ISO country codes between ISO 3166-1 alpha-2 and alpha-3 if necessary.

        This method takes a country code string (either ISO 3166-1 alpha-2 or alpha-3) and checks if a conversion is
        needed based on the `self.codes` attribute. If a conversion is required, it attempts to perform the conversion
        using the `ISO3TOISO2` or `ISO2TOISO3` dictionaries. If the conversion is successful, the converted code is
        returned; otherwise, the original value is returned.

        :param val: The value to be unserialized, typically a string representing an ISO country code.

        :return: The unserialized value, either the original or converted ISO country code.
        """
        if isinstance(val, str) and len(val) == 3 and self.codes == self.ISO2:
            # We got an ISO3 code from the db, but are using ISO2
            try:
                return self.ISO3TOISO2[val]
            except KeyError:
                pass
        elif isinstance(val, str) and len(val) == 2 and self.codes == self.ISO3:
            # We got ISO2 code, wanted ISO3
            try:
                return self.ISO2TOISO3[val]
            except KeyError:
                pass
        return val
